# Generated by Django 3.1.7 on 2021-03-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
