# Generated by Django 3.1.7 on 2021-03-19 14:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('sony', 'sony'), ('nikon', 'nikon'), ('canon', 'canon'), ('red', 'red'), ('fujifilm', 'fujifilm'), ('panasonic', 'panasonic'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('coding', 'coding'), ('tech', 'tech'), ('vlogs', 'vlogs'), ('comedy', 'comedy'), ('filming', 'filming'), ('gaming', 'gaming'), ('cooking', 'cooking')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
