# Generated by Django 3.2 on 2021-05-11 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacttuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('ph_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('comp_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
