# Generated by Django 3.2 on 2021-05-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0002_auto_20210511_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/about/')),
                ('desc', models.TextField()),
            ],
        ),
    ]
