# Generated by Django 3.2 on 2021-05-13 14:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0003_aboutinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
